### ISSUE TITLE
beautify markup is false if close-tag and nested start tag are attached

### ISSUE THREAD

**Issue by kaizer200** [prettydiff/prettydiff#123]
Hi,
(in XML file) nodeA is nested in nodeB. nodeA doesn't have an explicit closing tag (uses />) . nodeA is attached(right before) the closing-tag of nodeB.
In this case- the beatification is not ok (the closing tag of nodeB doesn't get indented in new-Line).
if there was a space between the closer of nodeA, and the closing-tag of nodeB - the beautification is ok.

sample example-A (no space between thirdTag closer and secondTag closer):
```
<dodo>
	<secondTag a="aa">
		<thirdTag b="bb"/></secondTag>
</dodo>
```
example-A false beautification result ( </secondTag> wasn't indented in new line as it should):
```
<dodo>
	<secondTag a="aa">
		<thirdTag b="bb"/></secondTag>
</dodo>
```

sample example-B (space between thirdTag closer and secondTag closer):
```
<dodo>
	<secondTag a="aa">
		<thirdTag b="bb"/> </secondTag>
</dodo>
```
example-B good beautification result ( </secondTag> indented in new line as it should):
```
<dodo>
	<secondTag a="aa">
		<thirdTag b="bb"/>
    </secondTag>
</dodo>
```

**Comment by prettydiff** [comment]
This behavior is intentional.  In markup languages that convey content for human consumption any amount of white space between tags is a text node. Forcing indentation around self-closing tags can introduce text nodes where they may not be wanted.

In the case where indentation is always wanted I created an option `force_indent` to supply the desired effect.

Everything appears to be working correctly so I will close this issue.  If you believe I have failed to identify the problem please reopen the issue and we will work through it.

**Comment by yuvalmorad** [comment]
Hi,
so you indent closing parent tab 
1. in case a text exist between open and close tag (in this case white pace serves as a text).
2. in case there is child open and close tag
I think it is more readable to intent also in the third case:
3. in case there is a self closing child tab
What do you think?

**Comment by prettydiff** [comment]
Here are some examples with the before and after separated by `----`.  Just let me know if there is a scenario I am missing use some dummy code like this.  The same rules apply to self-closing tags that apply to text and indentation works the same even if they are intermingled.

example

    <a><b/> </a>
    ----
    <a><b/>
    </a>

example

    <a><b/><c/> </a>
    ----
    <a><b/><c/>
    </a>

example

    <a> <b/></a>
    ----
    <a>
        <b/></a>

example

    <a> <b></b></a>
    ----
    <a>
        <b><b/>
    </a>

example

    <a><b><c/></b></a>
    ----
    <a>
        <b><c/><b/>
    </a>

example

    <a> <b/><c/></a>
    ----
    <a>
        <b/><c/></a>


example

    <a><b/> <c/></a>
    ----
    <a><b/>
        <c/></a>

example

    <a> <b/> <c/></a>
    ----
    <a>
        <b/>
        <c/></a>

example

    <a><b><c/> </b></a>
    ----
    <a>
        <b><c/>
        </b>
    </a>

example

    <a><b><c/> <d/></b></a>
    ----
    <a>
        <b><c/>
            <d/></b>
    </a>

example

    <a><b/> <d></d> <c/></a>
    ----
    <a><b/>
        <d></d>
        <c/></a>

**Comment by yuvalmorad** [comment]
Thanks for the detailed attention!
You covered all scenarios still one of them can be improved in my opinion
I would like to pick one sample:
<b><c/> </b>
------------ GOOD!
<b><c/> 
</b>
BUT
<b><c/></b>
----------
<b><c/> </b>

I would expect 
<b><c/> 
</b>

**Comment by prettydiff** [comment]
@yuvalmorad I edited your comment to apply markdown formatting.  When you are making comment in Github you can format the content with markdown rules and use the preview tab to what the formatted comment looks like before you post it.

If I edited your comment correctly it appears that you suggest `<b><c/></b>` should have a similar formatting to `<b><c/> </b>` which becomes

    <b><c/>
    </b>

I am going to disagree because I cannot know if the space before `</b>` is intentional and should be preserved or not. Likewise I cannot presume the negative case when the space is missing and if one should be there to force indentation.  All I know is what is provided and the least altering parsed result.

**Comment by yuvalmorad** [comment]
Hi
again thank... could not find how to put markup...
I just could not understand yet why the space should make a difference for parent tag close indentation?
If the child is a standard non self closing it behanves the same with or without a space
<a><b></b></a>  AND <a><b></b> </a>
both results in
<a>
      <b></b>
</a>
BUT 
<a></b></a> AND <a></b> </a>
results in different beautification....

**Comment by prettydiff** [comment]
Here is some additional background information: https://github.com/prettydiff/prettydiff/issues/110

The objective is to treat self-closing tags (what I refer to as singletons in the code) as text. I treat `<a><b></b></a>` and `<a> <b></b> </a>` the same, because these two samples do not contain self-closing tags.  I treat `<a><b/> </a>` differently because `<b/>` is a self-closing tag.

Perhaps this will make more sense if I explained this in terms of text content that is consumed by humans.

    <p> this is some text that starts with a space and some<em>is emphasized</em>.</p>

The default treatment when XML/HTML are parsed is to tokenize all white space into single space characters.  As a result the text can be indented immediately after the opening `<p>` tag, because it will appear the same and be consumed the same way to all humans.

Now look at the `<em>` tags.  These guys but right up against some text.  If I forcefully indented the text and tags it would be consumed very differently for humans.  It would parse into something like:

    this is some text that starts with a space and some *is emphasized* .

Instead of (correctly according to the original code)

    this is some text that starts with a space and some*is emphasized*.

In markup code that is consumed by humans self-closing tags often convey content directly, such as HTML's *input* tags.  As a result I provide the same rules on self-closing tags as I would for text.
