### ISSUE TITLE
export default class

### ISSUE THREAD

**Issue by enjoylife** [prettydiff/prettydiff#128]
What rule forces a new line to follow the `export` keyword when used like this.

```
export default class TableEditor extends React.Component {
...
}
```

which gets turned into...
```
export 
default class TableEditor extends React.Component {
...
}
```

**Comment by prettydiff** [comment]
The problem is not the word `export` but rather the word `default`.  I cannot find in any example or in the spec where `default` is used aside from switch statements and possibly with tail call optimization.  I will put in some extra logic so that the line (plus negative indentation) is not inserted if the token prior to default is of type `word`.

It will be a couple of weeks before I have this fix released. It took two seconds on my local..... but pushing code updates while I am out here doing military training is painful (and probably expensive).

**Comment by enjoylife** [comment]
No worries, and thanks for looking into it while so busy.

**Comment by prettydiff** [comment]
Available for testing at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml
