### ISSUE TITLE
CSS !important breaking padding/margin

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#135]
a {
        padding: 1.5em 0 2em 0 !important;
    }

Becomes

    a {
        padding: 0;
    }

https://github.com/Glavin001/atom-beautify/issues/492

**Comment by davidscotson** [comment]
Hi, 

is this fixed? I was about to file the same bug but searched and found this already existing one, but can't figure out if it's closed because it's already done and shipped and I just need to update or not.

One addition to the report, that I was going to report is the following weird behaviour:

input
```
.example {
    margin: 0 0 1em 0 !important;
    margin: 0 0 1em 0 !important;
    padding: 0 0 1em 0 !important;
}
```
output
```
.example {
    margin: 0 0 1em 0 !important;
    margin: 0;
}
```
So only the second margin is broken, but the padding disappears completely.

**Comment by prettydiff** [comment]
I can reproduce that at http://prettydiff.com/ so I have opened a bug https://github.com/prettydiff/prettydiff/issues/159

The issue to which this bug was originally opened for is fixed though the issue you are reporting is certainly related.  Please look to the linked issue for all following updated.
