### ISSUE TITLE
Separate modules of Pretty Diff

### ISSUE THREAD

**Issue by setzer17** [prettydiff/prettydiff#155]
Hi,
I think if there are separate modules, one for comparison only, another for beautification only... it will increase performance, and make it easier to customize the code.

**Comment by prettydiff** [comment]
I have pretty much written the code that way I just don't use a build process to put separate files into a single file. I just updated the documentation to discuss this last night:  http://prettydiff.com/documentation.xhtml#contribute_summary

So, you can see that for convenience I do have the code broken down into modules at http://prettydiff.com/lib .  Once ES6 modules become widely supported I will use multiple files for the code since the code is already logically organized into modules.

Please let me know if addresses some of your concerns.

**Comment by setzer17** [comment]
I myself am only interested in the diff functionality. So a version of Pretty Diff that's dedicated for finding differences would be nice. There are other people who only need the beatification functionality, etc...

**Comment by prettydiff** [comment]
I do have my diff code isolated in:

* https://github.com/prettydiff/prettydiff/blob/master/lib/diffview.js
* http://prettydiff.com/lib/diffview.js

I just need to extend the node-local.js file to use one of the libs in the case where the prettydiff.js file is absent.

**Comment by setzer17** [comment]
That will be nice (y)

**Comment by prettydiff** [comment]
I have not found a good solution for this.  If a module is not available upon request from the `require` keyword Node throws an error and exits the application.

I am going to close this issue as unresolved for this time, but please feel free to submit a pull request or reopen this issue with some sort of resolution to try.
