### ISSUE TITLE
reformatter: breaking long strings into smaller sometimes breaks \n

### ISSUE THREAD

**Issue by joeytwiddle** [prettydiff/prettydiff#165]
When I reformatted a JS file, the pretty-printer broke up the strings so they didn't get too long.

Unfortunately there are some places you should not break a string.  For example `\n` and `\t` and probably also longer Unicode literals, and octal and hex `\0xNNN` and ... ?

This is what I got:

    ...
    " 155, 135); border-bottom-width: 2px; border-bottom-style: solid; border-radius:" +
    " 5px; transition: background-color 0.2s linear; background: rgb(9, 179, 156); }\" +
    "n.bt:hover { color: rgb(255, 255, 255); background-color: rgb(10, 203, 177); }\n" +
    ...

Notice the end of the middle line. This file fails to parse!

Sorry ;)

**Comment by prettydiff** [comment]
I have a solution up at http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml and will launch the fix once I resolve issue #161.

You are correct in that Unicode references (\unnnn for 16bit and \unnnnn for 32bit) should not be broken as the plurality of characters constitutes a single character once parsed.  I determined that as far as this bug is concerned it doesn't really matter, because we are only talking about string literals and concatenation as the strings will be combined at execution time.  I just have to ensure I am not breaking the syntax by unintentionally escaping the quote containing the string.

I might be wrong, since I never use octal and hex reference in JavaScript, but it seems no slash is need to create the character reference.  In my testing `0x200` directly parses in number type 512 while `\0x200` generates an error.

**Comment by joeytwiddle** [comment]
Thanks for the fix. Based on what you wrote earlier, I just want to point out this situation:

    > "\uabcdef" === ( "\uabc" + "def" )
    Error: SyntaxError: Unexpected token ILLEGAL

**Comment by prettydiff** [comment]
Good point.  I am working that in right now.
