### ISSUE TITLE
Bug: prettifying shorthand property names inserts semicolon after single property

### ISSUE THREAD

**Issue by enjoylife** [prettydiff/prettydiff#196]
This happens in a .jsx file when the options are set to airbnb's style:

```
/*prettydiff.com styleguide: airbnb */

```

Before 

```
  onSettingChange = (a, b) => {
      let newObj = {a,b};
      let newObj2 = {a};
  }
```

After
```
  onSettingChange = (a,b) => {
  let newObj = {
      a,
      b,
    };
    let newObj2 = {
      a;
    };
  };

```

Simple example to paste into online editor to replicate:

```
 import React, {
  PropTypes
} from 'react';


class SideNav extends React.Component {

  

  constructor(props) {
    super(props);
    this.state = {};
   
  }


  render () {
  
    return (
      <div>
      </div>
    );
  }


};

export default SideNav;

/*prettydiff.com styleguide: airbnb */
```

**Comment by prettydiff** [comment]
Accidentally fixed in some experimental code I am working on.  Please see #181.

In 181 I am including new logic at parse time to create a global array named `depth`.  This array will store an array per each token parsed where the first child index is a name of the current container and the second index stores the token index of where this containment started.  This new logic is allowing me to make precise decisions on each token without any algorithmic help.

I am currently in the process of tearing out a lot of algorithmic logic that is now unnecessary and I hope to release the new code within the week.  You can get the new code now (though its still experimental) from the link provided in 181.

**Comment by enjoylife** [comment]
Awesome! :+1: 
Thank you for the details and such a quick response.
