### ISSUE TITLE
running from command line doesn't execute; shows help

### ISSUE THREAD

**Issue by aroder** [prettydiff/prettydiff#217]
After installing the prettydiff node module, any command line execution I attempt just displays the help output. 

> npm install prettydiff
> cd node_modules/prettydiff/
> node api/node-local.js source:"<file1>.xml" diff:"<file2.xml>"

I've tried with various combinations of options, but the above is from the guide page and should work as is. http://prettydiff.com/guide/diffcli.xhtml

I've also tried installing globally and using the prettydiff alias. Same result

**Comment by crooney** [comment]
Just came here to report the same problem. The last line of the usage reads:

Version: 1.15.17 Dated: 16 November 2015

**Comment by prettydiff** [comment]
Near the extreme bottom of the `api/node-local.js` file there is this code:

    if (options.help === true) {
        help = true;
    }

I will change it to the following in order to solve for this problem:

    if (options.help === true && (process.argv.length < 3 || options.source === undefined || options.source === "")) {
        help = true;
    }

The cause of the problem is the default instruction provided in the `.prettydiffrc` file that turns on the help messaging.  If you delete that file, or change its contents so that `options.help = true;` is removed the problem is voided.  The proposed solution allows the help messaging to be set by default, but then overrides that instruction for nearly all uses cases.  To prevent the override simply fail to populate the required `options.source` option.

This will launch this evening.

**Comment by crooney** [comment]
Thanks for tackling this so quickly. I deleted the line from .prettydiffrc and the problem remained. I pasted in the change you posted and still it remains. I will report back after upgrading to your new rev.

**Comment by crooney** [comment]
Sorry, that was my mistake: I was changing the local node_module version but running the globally installed one. Works as described now.

**Comment by prettydiff** [comment]
Published!

**Comment by aroder** [comment]
I grabbed version 1.16.0 and no longer have this issue. Thanks!
