### ISSUE TITLE
Can't run prettydiff using javascript

### ISSUE THREAD

**Issue by bpromasmb** [prettydiff/prettydiff#219]
When I try running this code:

    var args   = {
            source: "asdf",
            diff  : "asdd",
            lang  : "text"
        },
        output = prettydiff(args);

I get a bunch of errors:

![image](https://cloud.githubusercontent.com/assets/12829571/11479727/a5618548-977a-11e5-9e69-7cf8e6c27639.png)

Namely `Uncaught ReferenceError: csspretty is not defined` and `Uncaught TypeError: prettydiff is not a function`.

I'm using:

* prettydiff.js
* dom.js
* diffview.css

**Comment by prettydiff** [comment]
Would you mind describing how you are running the application?  It looks like you have set up a local service and then use the browser to connect Pretty Diff on the local service.

**Comment by bpromasmb** [comment]
I don't quite understand what you're asking. I'm building a rails app, and all I did was add the assets I mentioned to my app and try to run the script I pasted here.

**Comment by prettydiff** [comment]
In order to run the application using the provided api files you will need every file in the `lib/` directory.  The library files are written in a way that they can be used independently apart from the rest of the application if you are willing to wire up access to those libraries yourself.

If you want to run the application out of the box with absolutely no configuration then you will need files in this arrangement:

* prettydiff.js
* diffview.css
* index.xhtml
* api/dom.js
* api/node-local.js
* api/prettydiff.wsf
* lib/csspretty.js
* lib/csvpretty.js
* lib/diffview.js
* lib/jspretty.js
* lib/markuppretty.js
* lib/safesort.js

Perhaps I need to update the documentation to reflect this.  I could have old documentation out there indicating you needed fewer files.  About two months ago all the libraries were packaged into the prettydiff.js application file directly.

**Comment by bpromasmb** [comment]
It seems there have been big recent changes and the documentation hasn't caught up yet, so I'm having a lot of trouble implementing this.

Ok, after setting up a "prettydiff" directory in my application's vendor directory with exactly the structure you specified (including the xhtml file... Is this really necessary? I intend on making my own html page.) I get an error: `Uncaught ReferenceError: process is not defined` on the file `node-local.js`

**Comment by prettydiff** [comment]
The html file is only required if you want to run the tool in your browser.  The node-local.js file is intended to be run by Node.js on the command line where the word `process` is a reserved feature of Node.

I really should enhance the node-local.js file so that it can receive options directly as an object passed into a function parameter instead of just looking to the command line.

I updated the documentation about this issue last night.

**Comment by prettydiff** [comment]
If you are still continuing to have problems please let me know and we can work through it together.  I will close this issue now presuming it is resolved, but please reopen it if there are additional remaining concerns.
