### ISSUE TITLE
Optionally leave ternary statements on a single line

### ISSUE THREAD

**Issue by amacdougall** [prettydiff/prettydiff#226]
I notice that jspretty breaks ternary statements into multiple lines. For example:
```javascript
var foo = condition ? bar : baz;
```
becomes
```javascript
var foo = condition
  ? bar
  : baz;
```
It would be nice to provide an option toggling this behavior. I'm happy to add one and make a pull request.

**Comment by prettydiff** [comment]
You can check this out if you go to http://prettydiff.com/ignore/testlocation/index.xhtml and scroll all the way down the page.  It is the second to last option named `ternaryline`.

**Comment by amacdougall** [comment]
Awesome! I have a feeling that 95% of people will be happy with one option or the other.

### Deep Thoughts

As a matter of principle, I think it would be nice to provide a "do not reformat" value for almost every option.

For instance, I suggested a `none` option for https://github.com/prettydiff/prettydiff/issues/227 because our codebase has both oneline and multiline chains, based on wrap margin, dev preference, etc. I can imagine reasonable people having similar opinions about other formatting options: "X should be tool-enforced, but Y is up to the dev."

I think prettydiff's beautification component is an important project. There are not many other JS formatting options out there, and adding ES6+ support has been slow going. Prettydiff is way ahead of the game, and I hope it becomes more widely used. Adding ever-more-granular configuration options may help with that.

On the other hand, who says a tool must be all things to all people? I respect opinionated tools! I just worry that among JS formatters in particular, there aren't enough choices right now, which puts some pressure on the few existing tools to become more flexible.

As always, I'm willing to put my man-hours where my mouth is and help implement anything I suggest.

**Comment by prettydiff** [comment]
I will certainly take the third option (do not reformat) approach into consideration, but updates like that to every option will be very slow.  The problem is that users generally want every single line of code reformatted, if at the very least to apply correct indentation, even if they may choose to not have a certain rule or convention applied.  That said a "do not reformat" option value will still take some increased effort to ensure other aspects of the given code are still being applied and that I am not breaking things by not using some blanket die hard rule universally.

I am more than happy to come back revisit this with a renewed focus in the near future.  More immediately I really want to get TypeScript support added and some better analysis of XML and accessibility.

**Comment by amacdougall** [comment]
Definitely. A project like this is a hydra, and I agree that correctness trumps configurability—especially since the two are directly at odds.
