### ISSUE TITLE
Optionally leave method chains untouched

### ISSUE THREAD

**Issue by amacdougall** [prettydiff/prettydiff#227]
Currently the `methodchain` option can be set to indent all chains of two or more methods, or inline them all. It would be nice to have a third option, to simply leave method chains untouched. This would free developers to apply their own rules or aesthetics.

I'm happy to implement this and make a pull request.

**Comment by amacdougall** [comment]
I just noticed that tokens other than function invocations are being treated as chains, as well:
```javascript
alpha.something.beta();
// ..becomes...
alpha
  .something
  .beta();
```
I am not sure if this is the intended behavior.

**Comment by prettydiff** [comment]
I will likely change the `methodchain` option from a boolean to a string excepting named values

* none - Indent method chains only if they are already broken with white space, otherwise leave them chained onto a single line
* singleline - force method chains onto a single line
* newline - force method chains to be indented

I will continue to support the boolean values internally in order to avoid breaking changes.
