### ISSUE TITLE
why i use prettydiff,  there is more js code

### ISSUE THREAD

**Issue by nuptxxp** [prettydiff/prettydiff#234]
i use pretty like this:
prettydiff source:"old.json" diff:"new.json" readmethod:"file"  mode:"diff" report:"true"  color:"white" 

but when it generaters  ____old.json-diff.html, i mv it in web server index.html, 
the html has more js code,like:
function core__auto(a) { var b = [], c = 0, d = 0, join = "", flaga = false, flagb = false, output = function co... etc 
i don't want this js code, could i remove this js code comment ?
sorry for my english , thx

**Comment by nuptxxp** [comment]
![Uploading CJI@1YGL6{67F}HR~60]0%U.png…]()

**Comment by prettydiff** [comment]
The unpublished fix is located at http://prettydiff.com/ignore/testlocation/api/node-local.js

I will publish the fix in the next release, possibly within 48 hours.  At that time just run this command line:

    npm install prettydiff -g

If you need the fix right now or wish to verify the file is better than take the file I linked to and overwrite the file named `node-local.js` in your global install location for package prettydiff.  Sorry I cannot be more specific because the global install location differs by operating system, run time, version manager, and executing application.

**Comment by nuptxxp** [comment]
nice!  i fixed it by the js you provided, thx, so nice of you.
