### ISSUE TITLE
How to use prettydiff on the browser?

### ISSUE THREAD

**Issue by anik786** [prettydiff/prettydiff#248]
I'm getting extremely confused as to how to use this library in a normal browser.

Here's what I have so far

```html
<html>
<head>
    <script>
        var global = {},
                args   = {
                    source: "asdf",
                    diff  : "asdd",
                    lang  : "text"
                };
//                output = prettydiff(args);
    </script>

    <script src="bower_components/prettydiff/lib/csspretty.js"></script>
    <script src="bower_components/prettydiff/lib/csvpretty.js"></script>
    <script src="bower_components/prettydiff/lib/diffview.js"></script>
    <script src="bower_components/prettydiff/lib/jspretty.js"></script>
    <script src="'bower_components/prettydiff/lib/markuppretty.js"></script>
    <script src="bower_components/prettydiff/lib/safeSort.js"></script>

    <script src="bower_components/prettydiff/prettydiff.js"></script>
    <script src="'bower_components/prettydiff/api/dom.js"></script>
</head>
<body>
</body>
</html>
```

Note that I had to add a bunch of libraries in order to remove many of the console errors (something that is not documented)! 

Is there a minified version of this library as it is quite important for browsers???

Also I found that the variables need to be declared BEFORE the other script tags, which is also not documented.

However, I still have a console error:
`Uncaught TypeError: Cannot read property 'getAttribute' of undefined`

Is there just a simple example on how to use this plugin for the web?
Is this plugin even suitable for the web?

Please help!

**Comment by prettydiff** [comment]
Yes, all the supplied libraries in the project are required.  Perhaps I have mislead you with some outdated documentation if you believed otherwise.  I will audit the documentation later today for this.

The most convenient ways to obtain this tool in order from easiest to more manual are:

* NPM
* Bower
* clone from github
* manually download the files from the website (which are always updated to the latest version)

The only minified code is the CSS.  I used to minify the application code when the project ran on fewer files.  I found the effort to maintain an unminified version and a minified version across various different distribution channels to be not worth the effort considering the limited savings.

I am marking this issue as a defect of the documentation.  My tasks will be as follows:

* Audit documentation for outdated instructions
* Clarify use and installation steps in the documentation page and code comments
* Verify and document order of library request
* Provide a simple demonstration HTML

For the mean time use the actual tool's HTML as an example: http://prettydiff.com/

The JavaScript error occurred because you put the `script` tags in the `head` of the document.  It would quicken the page rendering and solve this error if you moved the script tags to the bottom of the page `body`.  In the mean time I will look into a resolution for this and publish it with the next update.

**Comment by prettydiff** [comment]
I am working on new documentation at http://prettydiff.com/documentation1.xhtml but I still have some CSS updates to perform before its ready for launch.

**Comment by prettydiff** [comment]
New documentation launched to http://prettydiff.com/documentation.xhtml and this leads me to want to audit the tool's total CSS and revising minor presentation details to be less and sharper.

**Comment by anik786** [comment]
This is good to know.

**Comment by prettydiff** [comment]
I have largely accomplished this issue by providing new documentation that is more accurate and friendly on the eyes.  The updated and refined CSS code will be tracked in the recently opened #253.
