### ISSUE TITLE
Who is using this?

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#250]
The download stats are all over the place and yesterday the application was downloaded about 483,000 times on NPM:  http://npm-stat.com/charts.html?package=prettydiff

Here is what I know:

* I guesstimate about 18,000 users come from the awesome atom-beautify package where it is primarily used to beautify LESS, SCSS, XML, and JSX: https://atom.io/packages/atom-beautify
* Based upon past issues I know there is some amount of usage directly on the command line but I don't know how much
* Most of the NPM downloads come from either outside NPM or from declaring this application as a devDependency.  If packages are using this application as a devDependency I don't know which ones.

I have absolutely no idea where the traffic is coming from, who is using this, and why anybody would choose this application.  I cannot make this application better if I don't know what *better* means and I can't define *better* unless I know something about the users.  In the mean time I will continue to:

* find and patch defects
* improve the documentation
* fulfill requests

**Comment by animecyc** [comment]
I've been using PrettyDiff for quite some time now, mostly due to the amount of customization I can have with the languages I use it with (`css`, `html`, `xml`, and `javascript`). If I could have it my way I'd like to see more formatting options for ES6.

Keep up the fantastic work, it is much appreciated -- I'm sure everyone who uses this would agree.

On a side note: I'd also like to see `atom-beautify` add support for a `.prettydiffrc` file so that we can start using options it doesn't otherwise support.

**Comment by prettydiff** [comment]
@animecyc Thanks for the kind words.  I am a maintainer on atom-beautify now, so I will start working on pull requests for the remaining options in the near future.
