### ISSUE TITLE
Invalid formatting for es6 class with method `from`

### ISSUE THREAD

**Issue by animecyc** [prettydiff/prettydiff#251]
Seems like there is an issue when creating an ES6 class that happens to have a method called `from`; Pretty odd, it doesn't seem to happen with any other method name...

---

**Input:**
```javascript
class Test {
    foo() {}
    from() {}
    bar() {}
}
```
**Output**
```javascript
class Test {
    foo() {} from() {}
    bar() {}
}
```
**Expected**
```javascript
class Test {
    foo() {}
    from() {}
    bar() {}
}
```

**Comment by prettydiff** [comment]
This is an oversight on my part.  `from` does receive special treatment as it is a keyword used with import/export: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

I will need to be a bit more intelligent about the context to determine if `from` is a reference or keyword so that it can be beautified properly.
