### ISSUE TITLE
JSX As Argument

### ISSUE THREAD

**Issue by andrewjmead** [prettydiff/prettydiff#261]
First up, thanks for the awesome work.

The code in question it the following:

```
renderer.render(<MyComponent items={[1, 2, 3]}/>);
```

When I run it through prettydiff I get the following output which breaks the code.

```
renderer.render(< MyComponent items = {
  [1, 2, 3]
} />);
```

It seems to work find if I first declare the variable and pass that in. For some reason it's not enjoying the JSX being passed in as an argument. The code below gets formatted just fine in the end:

```
const componentToRender = <MyComponent items={[1, 2, 3]}/>
renderer.render(componentToRender);
```

Any ideas on what I can do to fix this? I tried a few different components but nothing seems to work.

Thanks!

**Comment by prettydiff** [comment]
I examined this in the lib/jspretty.js file and it turns out that I am being too cautious:  https://github.com/prettydiff/prettydiff/blob/master/lib/jspretty.js#L1893

It seems in your code you have aliased the React object and I am not detecting this properly.  I tested the code after removing the bit about `token[d - 2]` and `React` and it works correctly.  I am examining alternate safeguards to ensure I am properly identifying markup tags while not breaking valid JavaScript.  A solution will launch in the next update.

**Comment by prettydiff** [comment]
Would you mind testing out a quick solution for me?

http://prettydiff.com/ignore/testlocation/lib/jspretty.js

Replace the copy of the lib/jspretty.js with the file in the link and see if that fixes or breaks your code.  It passes all my unit tests.  It just makes a flat assumption that JSX tags are

* single angle brace delimited
* immediately start with an XML reference appropriate character or exclamation character `!`
* immediately follow an operator, `return`, or `(`

This is far more generic and allows any amount of aliasing.

**Comment by andrewjmead** [comment]
Hey @prettydiff. This works! I can't thank you enough for the fast response. I'm glad we got to the bottom of it :smile:.
