### ISSUE TITLE
output diff to html

### ISSUE THREAD

**Issue by bhuvangu** [prettydiff/prettydiff#271]
When running the following command i get the diff as html , but the right side of diff is `b.java` instead of content of `b.java`

`prettydiff source:"a.java" readmethod:"auto" diff:"b.java" lang:"text" readmethod:"auto" mode:"diff" diffcli="false" > out.html`

**What am i doing wrong?**

Also when i change the `readmethod` to `file` the output is always text not html

`Version: 1.16.17 Dated: 16 February 2016`
`node v0.10.36`
`npm -v 1.3.6`

**Comment by prettydiff** [comment]
I cannot reproduce any defect.  I ran the exact command line instruction you specified and got a perfectly formatted file named out.html that I was able to open in my browser.

The `file` readmethod value is for reading from files.  In this case we are not reading input from files, but instead are supplying it directly.

**Comment by bhuvangu** [comment]
https://drive.google.com/file/d/0B7mODeoXP_hEYXdOMjZvdFpiMUk/view?usp=sharing

my complete test folder.

I am using `centos7`.

Did you tried with `Version: 1.16.17 Dated: 16 February 2016` version?

**Comment by bhuvangu** [comment]
Also

`prettydiff diffcli=false source:"a.java" diff:"b.java" readmethod:"file"`

gives me a color text output on console instead on html

**Comment by prettydiff** [comment]
Thanks to your download I can reproduce the defect.  File `a.java` is read while string `b.java` is the compared string.

**Comment by prettydiff** [comment]
The `auto` value of readmethod option does not resolve to a value of `file`.  The value `file` expects to receive input from files and write output to a file.  When readmethod is `auto` and the input is files is resolves to a value of `filescreen` which expects to read output from files and output to screen.  I should probably change this, but it is set up that way to prevent errors in the case where the `output` option isn't specified.

As for this specific matter the defect is: https://github.com/prettydiff/prettydiff/blob/master/api/node-local.js#L2287-L2291

The correct code is:

    options.diff = dfiledump[data.index];
    options.source = sfiledump[data.index];

The readmethod `file` option appears to be working correctly if an `output` directory is provided.  If not the `diffcli` option is activated.

The use of options in this manner is clunky instead of just piping to a file directly.  I do this intentionally though for cross OS/file system support.

**Comment by prettydiff** [comment]
Did the previous comment answer all your questions and identify all the defects?  I will publish the resolution soon and I hope there is anything I failed to consider.

**Comment by bhuvangu** [comment]
damm!!! you are one humble guy on internet.

>  I hope there is anything I failed to consider.

I think all are considered

**Comment by prettydiff** [comment]
Closed with v1.16.18.
