### ISSUE TITLE
escape single quote in jsx

### ISSUE THREAD

**Issue by sizeon** [prettydiff/prettydiff#293]
It is acting weird when you have a backslash + single quote in jsx.
`<div>
  {'test\'test'}
</div>
`

**Comment by prettydiff** [comment]
I found the problem is https://github.com/prettydiff/prettydiff/blob/master/lib/markuppretty.js#L1035

    } else if (b[a] === quote.charAt(quote.length - 1)) {

Needs to become

    } else if (b[a] === quote.charAt(quote.length - 1) && ((global.jsxstatus === true && end === "}" && b[a - 1] !== "\\") || global.jsxstatus === false || end !== "}")) {

The markup parser wasn't smart enough to account for escaped quotes of JavaScript fragments of JSX.  I will release this fix with version 2, which I am trying to wrap up as rapidly as possible.

**Comment by prettydiff** [comment]
Fixed with the 2.0.0 release
