### ISSUE TITLE
Web site is down :(

### ISSUE THREAD

**Issue by ValentinH** [prettydiff/prettydiff#328]
![image](https://cloud.githubusercontent.com/assets/2678610/17018058/4d365f6e-4f36-11e6-911f-9271ad0c0b24.png)

**Comment by prettydiff** [comment]
Weird.... It is up right now so it must be some kind of server outage.  I will review the logs after my morning exercise and post exactly what I find.

**Comment by ValentinH** [comment]
Yes, it's working fine here too now.

**Comment by prettydiff** [comment]
I am having trouble finding any logs about why the server went down.  Since then I have started trying to enable HTTPS and haven't had any luck there either.  I got a certificate created for my domain and verification from Let's Encrypt, but cannot seem to make it work.  It seems I might need to enable some Apache config that I am unaware of.

**Comment by prettydiff** [comment]
I have no idea why the website went down when it did.  I could not find anything in the logs.
