### ISSUE TITLE
Bad formatting with mixins styles

### ISSUE THREAD

**Issue by raky291** [prettydiff/prettydiff#329]
# Description
I'm using the default beautifier (Pretty Diff), if I use CSScomb the result it is correct.
The results of beautification are not what I expect.

# Expected Results
The beautified code should have looked like:
```
// Mixins Styles
.make-cols(@xs:12, @sm: @xs, @md: 6, @lg: @md) {
    .make-xs-column(@xs);
    .make-sm-column(@sm);
    .make-md-column(@md);
    .make-lg-column(@lg);
}
```
# Output Results
```
// Mixins Styles
.make-cols(@xs:12, @lg: @md),
@md: 6,
@sm: @xs {
	.make-xs-column(@xs);
	.make-sm-column(@sm);
	.make-md-column(@md);
	.make-lg-column(@lg);
}
```

# Steps to Reproduce
Use my code and run command `Atom Beautify: Beautify Editor`

**Comment by prettydiff** [comment]
This issue is already fixed.  Try it for yourself at http://prettydiff.com/?m=beautify

The current published version of Pretty Diff is 2.1.0, but Atom Beautify is using 1.16.37, because this is the last version I updated to NPM.  I had some disagreements with NPM and chose to bail out.  I am currently working on an alternative right now at https://github.com/prettydiff/biddle
