### ISSUE TITLE
Reading local files for diff

### ISSUE THREAD

**Issue by VWTypeIII** [prettydiff/prettydiff#339]
Hello is there an example of the URL needed to invoke prettydiff from an HTML page, where I can pass a local file names to prettydff and it will read the files and report on the differences?  s and d tags with local URIs seem to be interpreted as literals, and do not seem to be seen  by prettydiff as file references to be read and the content of the files then analyzed.

Thanks

**Comment by prettydiff** [comment]
How Pretty Diff executes this is by reading the URI as a string literal.  If the api/dom.js file believes this to be HTTP(s) address it then issues an asynchronous request to http://prettydiff.com/proxy.php with the URI as a parameter.

Reading files from URIs is problematic due to cross domain security.  Web browsers and only make asynchronous requests to the identical domain from which the requesting code was originally served.  To get around this on my domain I use a small PHP file to act as a proxy to bound HTTP requests outside my domain and outside a web browser.  It just verifies the issuing request came from my domain, issues a curl, and then returns the result as a string.

If you are trying to execute the web tool elsewhere, even on your localhost, you will need to reconfigure this PHP file to work for you or find an alternate solution: https://github.com/prettydiff/prettydiff/blob/master/proxy.php

If this fails to answer your question please let me know.

**Comment by VWTypeIII** [comment]
Thank you, this is very helpful
