### ISSUE TITLE
Added space in SCSS Mixin

### ISSUE THREAD

**Issue by alexranc** [prettydiff/prettydiff#357]
Hi there,

First of all thank you for an amazing tool!

When using this via Atom Beautify or via gulp-prettydiff I am getting an added space within a mixin.

**Original Code**

```
@mixin color-darken($color__name) {
    @include color($color__name);
    @include default-transition(color, background);
}

```

**Output**

```
@mixin color-darken($color__name) {
     @include color($color__name);
    @include default-transition(color, background);
}
```

Any ideas why it would add this extra space?

Thank you

**Comment by prettydiff** [comment]
I am having trouble reproducing this on http://prettydiff.com/  It could be that there is a defect related to the options you are using.  Would you mind producing Atom Beautify's debug.md and pasting that into a gist?  That way I can see what options you have selected and better attempt to reproduce the problem.

**Comment by prettydiff** [comment]
A nearly identical problem was just reported in Atom Beautify. https://github.com/Glavin001/atom-beautify/issues/994

I can reproduce the problem in Atom Beautify.  The problem is that Atom Beautify is using the latest version of Pretty Diff available from NPM.  I had some disagreements with NPM and made the decisions to not update my code there anymore.  I have since fixed this problem, which is why I cannot reproduce the problem outside Atom Beautify.

I am working on an alternative to NPM and promise to dedicate time to it this weekend.

https://github.com/prettydiff/biddle
