### ISSUE TITLE
How to inline ignore scss/css?

### ISSUE THREAD

**Issue by adi518** [prettydiff/prettydiff#406]
Failed to find it myself. Is it even possible? using Atom Beautify here.

Thanks.

**Comment by prettydiff** [comment]
Can you give me a brief code example of what you are looking for?

**Comment by adi518** [comment]
`/* prettydiff: ignore start/end /*`

Something along that. I have a piece of code that seriously messes up the code when attempted to beautify:

`@include mixin('param1', 'param2') {
...
}`

I have a bunch of these mixins and they are nested so that's probably what is causing the bug.

**Comment by prettydiff** [comment]
Oh, then it just sounds like a defect in my code.  Are you using Pretty Diff from Atom Beautify?  The code sample appears to beautify correctly in the latest version of Pretty Diff when I run it through http://prettydiff.com/?m=beautify

**Comment by adi518** [comment]
Yes, this is on Atom with Atom Beautify in it's latest version.

**Comment by prettydiff** [comment]
Yeah, so this is probably a defect that is long since resolved.  The version of Pretty Diff in Atom Beautify is 1.16.37 from March or April 2016.  The current version of Pretty Diff is 2.1.15 from about a month ago.

The lapse is because I have had a falling out with NPM.  I am determined to get Pretty Diff updated in Atom Beautify and I have written a new package manager to make this happen.  I have just finished some major work to ensure stability on all OSs.

This new package manager is https://github.com/Unibeautify and it is created for the needs of Unibeautify, https://github.com/Unibeautify.  The goal is to eventually wind down support of Atom Beautify and instead ramp up work on an independent project that works in many IDEs and other applications.  This means the package manager has to work in many operating systems (NPM does this) and support applications written in many different languages (NPM doesn't do that) and allow automated publication of application in various forms (NPM does do that either).

It also will never have the problem of NPM's leftpad failure, because the there is no central repository.  Instead the published application will be self-hosted at the developer's expense.  With that you get private modules for free, immunity from censorship (such as the trademark problem that triggered the Leftpad failure), and dramatically less fragile software which is great for the users (particularly for our Chinese users who **hate** NPM module resolution behind the great firewall).  The limitation is a minor loss of convenience.

Anyways... before I tell Glavin at Atom Beautify that biddle is stable and ready I need user support to test and play around with it.  While it seems stable for me I am on the only person playing with it.  Once other people claim it works well at automatically installing software then I will have it included in Atom Beautify.

**Comment by adi518** [comment]
I managed to temporarily by-pass the problem by omitting the single quotes where I pass 2 params. That what seems to have triggered it, although there's another small issue, but non-breaking, that collapses the space after the comma.

**Comment by michaelroper** [comment]
Out of interest, was there ever anything implemented like the suggestion above, that lets you ignore a line/block of code? A VS Code extension that I use for formatting Twig uses PrettyDiff, but I don't want it to beautify a block of inline CSS. Is there any way to stop it from doing this?

Also, just looking at UniBeautify - is this another way to solve this? Will it let me use Prettier for the inline CSS and PrettyDiff for the Twig in the same file?

**Comment by prettydiff** [comment]
Pretty Diff 3 has not launched yet, but its getting very close.  Support is already in Pretty Diff 3 for this feature: https://github.com/Unibeautify/parse-framework/blob/master/docs/tech-documentation.md#ignore-code
