### ISSUE TITLE
Support for eslint rules.

### ISSUE THREAD

**Issue by love2dishtech** [prettydiff/prettydiff#412]
Hi,

Is there any plan to provide support for eslint rules. Either a direct support or a set of configuration options enough to let it be tuned as per the linting rules.

I am  using airbnb linting rules configurations and the JS/JSX are way different from defined rules after beautification.

**Comment by prettydiff** [comment]
The Pretty Diff beautifier has an option called `styleguide` that can contain a collection of settings to conform to a given style guide.  This will probably be the best bet.  I will look at this tomorrow to see what rules need to be put together to achieve a ESLint rule set.

**Comment by prettydiff** [comment]
Is there an official set of ESLint style rules?

**Comment by love2dishtech** [comment]
Yes that's the one. There are lot of particular adoptions as a subset or sort of convention. One of them quite widely used is the Airbnb guide for eslint rules. Here's the link: 
1) https://github.com/airbnb/javascript
2) https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

**Comment by prettydiff** [comment]
I do have some airbnb style guide options already preconfigured in the tool.  Just set the option `styleguide` value to `airbnb`.  It has been a long time since I have looked at these settings, so if you find there are qualities of the airbnb style guide I am not accounting for please reopen this issue and I will get those items corrected.
