### ISSUE TITLE
Circular dependency issue when included via require.js

### ISSUE THREAD

**Issue by prettydiff** [prettydiff/prettydiff#435]
The libraries markuppretty.js and jspretty.js depend on each other.  There is a report that this co-dependency is resulting in a circular problem when included via require.js.

**Comment by murrayju** [comment]
I made an example repo [murrayju/prettydiff-test](https://github.com/murrayju/prettydiff-test) that shows how I'd like to use prettydiff with requirejs. This of course immediately breaks because `global` is undefined. 

I'm really close to hacking together a workaround by manually defining all of the dependencies and shimming in the requirejs config, but this is incredibly complex and brittle.

I think ideally you could use webpack/rollup/etc to bundle all of your code into a single library that doesn't have any dependencies, making it far easier to consume.

**Comment by murrayju** [comment]
As far as my workaround goes, I'm getting stuck here (in prettydiff.js line 473):
```js
//requirejs support
define(function requirejs(require, module) {
    module.exports.edition = global.prettydiff.edition;
    module.exports.meta    = global.prettydiff.meta;
```
Which leads to the runtime error `Unable to set property 'edition' of undefined or null reference` (Because `module.exports` is `undefined`). I think the problem here is that the wrong arguments are being passed to requirejs. According to the [requirejs docs](http://requirejs.org/docs/commonjs.html#manualconversion), the function on line 472 should have the signature
```js
define(function (require, exports, module) { ... });
```

**Comment by prettydiff** [comment]
I just got this working on my local.  I need to do some clean up and validation before I commit, but you should have a working solution before tomorrow.

**Comment by prettydiff** [comment]
The updated code is in the 2.2.0 branch.  Please see the new directory test/barebones to see how I got this to work.

**Comment by prettydiff** [comment]
I am closing this.  I am going to keep with old school vanilla JavaScript approaches.  The application can be included into HTML using HTML script tags or by integrating the Pretty Diff application into your application's build system.

Pretty Diff integrates JavaScript into its webtool HTML using these files:

1. prettydiff/node_modules/parse-framework/js/browser.js
1. prettydiff/js/dom.js

To integrate the Pretty Diff into other HTML use these files instead:

1. prettydiff/node_modules/parse-framework/js/browser.js
1. prettydiff/js/prettydiff.js

The `prettydiff.js` is a vanilla JS function with no dependencies and is completely environment agnostic.  The `browse.js` file contains a single binding the to the browser's `window` object.
