### ISSUE TITLE
CLI with readmethod:file and mode:diff produces no output file

### ISSUE THREAD

**Issue by TGabor** [prettydiff/prettydiff#444]
`node api/node-local.js readmethod:file output:o.xml source:a.xml diff:b.xml mode:diff`
produces no output file.
When using `mode:beautify`, an output is generated.

Is this intended behaviour?

This happens both under Windows 7 and Ubuntu with Node v6.10.3

**Comment by prettydiff** [comment]
Found the problem: https://github.com/prettydiff/prettydiff/blob/master/api/node-local.js#L746

There is some extraneous code at the end of that code line, a secondary condition that shouldn't exist.  I will merge this to master soon!

**Comment by TGabor** [comment]
Thanks! Seems to work now :)
However I noticed a bug in the output.

1) If the two files differ, I get this output on my terminal
```
File successfully written.

Pretty Diff found 0 differences. Executed in 0.14 seconds.
```
The second line should probably state a number greater than zero.

2) If the two files are identical, I get this output:
```
Pretty Diff found 0 differences. Executed in 0.047 seconds.
```
But no file is written in case the two files are identical.

**Comment by prettydiff** [comment]
Thanks, I am looking into this.

**Comment by prettydiff** [comment]
I am having trouble reproduce this defect with the difference count, but I have also made some enhancements for another issue.

* Before today the diff library was removing carriage return characters before running the comparison.  Now they are treated like other text characters.
* White space differences are now explicitly called out with text messaging in the output instead of simply outputting the literal white characters, which are hard to identify.
