### ISSUE TITLE
Distribute as a single js file

### ISSUE THREAD

**Issue by murrayju** [prettydiff/prettydiff#458]
It is currently quite difficult to consume this like other javascript libraries. Most libraries are distributed as a single js file that is bundled up as a module that can be loaded with any of the common module loader systems (typically using a UMD wrapper).

The current state seems to be several js files that need to be strung together in a very particular way, depending on loading them synchronously, and with some state in the global scope.

This library would be much more useful if it worked as an isolated module.

**Comment by murrayju** [comment]
This is closely related to #435.

**Comment by prettydiff** [comment]
This is a great idea.  I really could get this down to three JS files.  The application file and the two API files.  It would be big though, like 40k lines of code.

This weekend I started working on the opposite approach... breaking some of the big files apart.  I have been thinking for a while that I am better at writing parsers than the beautification logic and so wanted to make my parsers available as independent files.  Many files is convenient for this use case and for people who wish to contribute to the code, but it is a huge pain the ass to properly distribute, configure into a page, and manage.

I really want to do this for my own sanity, so before breaking anything else down into smaller files I need to figure out the ideal approach to solve all needs.  Maybe introduce a build step to bundle files together.

**Comment by murrayju** [comment]
Yes, I'd highly suggest breaking the source up into several logical modules (for all of the reasons that you stated), and then use something like Webpack or Rollup in a build step to produce the combined library module bundle.

**Comment by murrayju** [comment]
To add to that... If you think it makes sense for some of these modules to stand on there own as useful modules/projects, you could split them out into their own repos and pull them into this one as dependencies. I like the idea of this being pluggable such that you could swap out different parsers/beautifiers easily, but for convenience sake I'd still like to see a "default" bundle that includes your standard implementation of the whole pipeline.

**Comment by prettydiff** [comment]
My plan for this issue is:

* merge the libraries back into the prettydiff.js file creating a colossal file with nearly 30k lines of code
   * reorganize the code to remove any redundant references and create a more logical hierarchy of functions
* write a utility that accepts a name and walks an application to return all functions by that name as a string type, so that anybody can access fragments of the application
* externalize the parse tree so that it can be called by reference after any operation

**Comment by murrayju** [comment]
> write a utility that accepts a name and walks an application to return all functions by that name as a string type, so that anybody can access fragments of the application

Can you elaborate on this? It sounds like you are suggesting that the public API would be some sort of string matching reflection?

**Comment by prettydiff** [comment]
The idea behind that is if somebody wanted to pull out a parser or some utility or anything else I will help them do it.  There are two and a half things I want to externalize to speed my maintenance and make the code more available to potential contributors.

* In the node.js execution of the tool I provide a means to just output the options object before the prettydiff function executes.  That way anybody see all of the settings that are passing in after all human interaction is accounted for.  This is really helpful when things act one way, but you think they should be acting another way because the option values are different than what you were expecting.  I want to make this universally available.
* When I attempt to troubleshoot the parse or beautification operations I dive into the code and set some `console.log` statements to output some of the parse tree.  Currently, this stuff is just an internal variable in a function so you cannot get to it directly without using a code editor.  After I pass some code through the prettydiff tool I should be able to call via reference this parsed data without running the tool again.
* Finally, when I merge everything into a single file people will be intimidated.  At the start of this project 8 years ago it was a single file (only about 5 lines) and people found that intimidating.  In order to temper some of these fears I want write a utility to extract functions, as strings, by name.  That way a developer can make some modifications to a returned code fragment without diving into the monster code file.  I have worked out (in my head) how to do with this as a read operation, but yet how to do this as a write operation (replace the existing function with your modified one).

**Comment by bitwiseman** [comment]
@prettydiff I didn't see you address the question of why not use a tool like Webpack.  To me, no matter how logically laid out, a single file is still harder to understand than a well laid out folder structure.

**Comment by prettydiff** [comment]
This is done in Pretty Diff 3.  Pretty Diff's webtool uses two files:

1. prettydiff/node_modules/parse-framework/js/browser.js
1. prettydiff/js/dom.js

If you wish to use your own HTML simply substitute the `prettydiff.js` file for the `dom.js` file, such that:

1. prettydiff/node_modules/parse-framework/js/browser.js
1. prettydiff/js/prettydiff.js
