### ISSUE TITLE
prettydiff2 npm package

### ISSUE THREAD

**Issue by runn1ng** [prettydiff/prettydiff#490]
What exactly is this npm package
 
https://www.npmjs.com/package/prettydiff2

In here, I see that prettydiff2 is not on npm - #291 - but there is prettydiff2 package there. How is it related?

(I don't want to talk about politics here, I just want to know what is in the npm package :))

**Comment by prettydiff** [comment]
package | version
---|---
prettydiff | 1.16.37
prettydiff2 | 2.2.7

I had a falling out with NPM for several reasons so I chose to never update to NPM again.  I cemented this by changing the version on NPM to 99 and since NPM forces semvar I would have to change this application to version 100 in order to publish again on NPM.

A few months ago Glavin of Atom Beautify asked me publish on NPM again so that the far updated Pretty Diff version 2 could be tested with Atom Beautify's wide audience as we prepare work for the upcoming Unibeautify project.  In agreement I published the updated version of Pretty Diff as NPM package "prettydiff2".  A pull request integrating the latest version of Pretty Diff into Atom Beautify was recently completed and merged, but it is not yet published to APM.

Pretty Diff is currently 2.2.9, so I need to publish an updated to prettydiff2 npm package.
