### ISSUE TITLE
No metadata returned from `prettydiff.api`

### ISSUE THREAD

**Issue by jonnyreeves** [prettydiff/prettydiff#54]
According to the API documentation, `prettydiff.api`'s return value should provide metadata about the diff in the second element; however when I run the following code the second element is always empty.

```
var prettydiff = require('prettydiff');

var output = prettydiff.api({
    source: '<p>hello</p>',
    diff: '<p>goodbye</p>'
});

console.dir(output);
```

###### output
```
[ '<?xml version=\'1.0\' encoding=\'UTF-8\' ?><!DOCTYPE html PUBLIC \'-//W3C//DTD XHTML 1.1//EN\' \'http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd\'><html xmlns=\'htt ... {snip} ... </body></html>',
  '' ]
 ```
 
 I am using prettydiff `^1.8.19`, installed via NPM.
 
 My goal is to simply determine if two HTML files contain any differences leverging the power of prettydiff's fuzzy matching (ie: ability to ignore whitespace / bracing inconsistencies)

**Comment by prettydiff** [comment]
The meta data current looks something like:

    <p>Code type set to <strong>auto</strong>. Presumed language is <em>JavaScript</em>.</p><p><strong>Execution time:</strong> <em>0.013 seconds </em></p><p><strong>Number of differences:</strong> <em>1</em> difference from <em>1</em> line of code.</p> <p>Accessibility note. &lt;em&gt; tags in the output represent presentation for variable coloring and scope.</p>

It conveys (in HTML):

* Presume language (if lang option is value "auto")
* Execution time in seconds
* Number of total differences and number of lines in which those total differences occur
* A note about accessibility for the generated HTML

I need to change the documentation to be more clear. The output of the prettydiff application library is always an array of two indexes for predictability. The meta data is really only broken out separately for the minify and beautify options. There is a means to break away this meta data from the actual diff results in the prettydiff library, but I am not exposing this to the node-local.js library.  Currently this information is integrated into the top of the HTML formatted diff report. I will expose this capability to the command line when I publish the next update, just pass an option named "api" with any string value.

From reading your intentions it sounds like you might be happier with command line out instead of an HTML file:  http://prettydiff.com/guide/diffcli.xhtml
