### ISSUE TITLE
Status of 3.0?

### ISSUE THREAD

**Issue by bluepeter** [prettydiff/prettydiff#568]
Hopefully soon?

**Comment by prettydiff** [comment]
It is published online and at NPM:

* https://prettydiff.com
* https://www.npmjs.com/package/prettydiff

I am using version 100 because I wanted to use the original NPM package name that had been sitting at v99 for years and I didn't realize I could unpublish releases.  I have not integrated it into any of the IDEs yet though.

Just let me know if you have any additional questions.

**Comment by bluepeter** [comment]
Perhaps you need to bump https://github.com/prettydiff/prettydiff/releases because this doesn't look like the latest? Screenshot:

<img width="954" alt="screen shot 2019-02-12 at 7 49 51 am" src="https://user-images.githubusercontent.com/2158187/52648148-d8e15c80-2e9a-11e9-8622-59752e8c2dc5.png">

**Comment by prettydiff** [comment]
Thank you!  I just bumped the release on the repo.
