### ISSUE TITLE
Deletes entire files on save

### ISSUE THREAD

**Issue by mblode** [prettydiff/prettydiff#582]
I've tried using this formatter with my twig code, but it's way too volatile. Some files get completely deleted and all the text inside the document is gone. Some files on save delete a large amount and leaves internally placed javascript code behind and no trace of any other code.

This is an issue in the Twig Language extension on VS Code

```html

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="ie=edge" http-equiv="X-UA-Compatible">
        <title>Document</title>
    </head>
    <body>
        <script>console.log("Hello")</script>
    </body>
</html>
Then when I beautify as HTML it becomes...

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="ie=edge" http-equiv="X-UA-Compatible">
        <title>Document</title>
    </head>
    <body>
        <script>console.log("Hello")</script>
    </body>
</html>

```

But finally, if I run the formatter for a second time, the contents of the beautify become...

```js

console.log("Hello")

```

This is breaking formatting for many people who have a script tag within their HTML file. How can I fix this issue?

**Comment by prettydiff** [comment]
I have attempted to reproduce this behavior, but cannot reproduce it.  I saved the suggested code sample to a file I named *twigtest.txt*

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="ie=edge" http-equiv="X-UA-Compatible">
        <title>Document</title>
    </head>
    <body>
        <script>console.log("Hello")</script>
    </body>
</html>
```

Executing from the command line using Node I run this command:

`node js/services beautify ..\twigtest.txt output:"..\twigtest1.txt" crlf:true`

The output appears identical to the provided input.  I then try again with this command:

`node js/services beautify ..\twigtest1.txt output:"..\twigtest2.txt" crlf:true`

Again, the output as written to the new file is identical.  Does my process differ from the process you are using?

**Comment by mblode** [comment]
@prettydiff I've updated my VS Code extension to ignore script tags when it parses the document which is functionally like:

```html

<script data-prettydiff-ignore>
  console.log("H")
</script>

```

This has officially fixed the issue but thank you for your help 👍

**Comment by prettydiff** [comment]
I am looking over this in greater detail.  I down loaded the VS Code extension for twig.  When I choose right click and format nothing happens.  When I try shift+alt+f nothing happens.  I am using the code from above pasted into a file named test.twig.

I want to be able to step through the extension code to see where the failure occurs so that I can revise my documentation and make necessary code changes.

https://github.com/mblode/vscode-twig-language-2/blob/master/src/extension.js

**Comment by mblode** [comment]
Sorry about that! I was experimenting with an if statement that checks if it is an HTML block or style block or script block. However, it didn't seem to work. I've pushed version 0.7.4 to revert this line of code and I've tested it on a blank VS Code install and everything is working smoothly 👍

**Comment by prettydiff** [comment]
I think I may have figured out the problematic behavior.  If Pretty Diff's default settings are saved or cached anywhere, such as storing the object in memory within your own application, internal changes to settings become the active defaults.

The key options of concern are:
* end
* indent_level
* start

Pretty Diff uses those three options to know when to switch between different sets of rules.  I am working on a resolution as this is my problem.  However, you can test if I have correctly identified the problematic behavior by setting each of those options to `0` after each call to `prettydiff.mode`.

The solution to this problem, on the Pretty Diff side, will be to eliminate the *end* and *start* options and pass in a starting indentation value instead of reading from the options.  This is a breaking change to the API so it will require a new major version even though it is a fairly small change.
