### ISSUE TITLE
How to use object_sort to sort html tags attributes ?

### ISSUE THREAD

**Issue by driplo** [prettydiff/prettydiff#587]
Hello,

I have trouble using the option `object_sort` with the beautify mode in nodejs, this is what I do but it doesnt seems to work:
   ```
 const beautifyOptions = {
      source: myHTML,
      mode: 'beautify',
      object_sort: true,
    }
    prettydiff(beautifyOptions)
```

**Comment by prettydiff** [comment]
Try using the option *tag_sort* to sort markup.  I made these separate options in case somebody had JavaScript or CSS embedded in an HTML document and wanted to sort either those or the HTML but not both.

**Comment by driplo** [comment]
Hi, thanks for your answer, unfortunately this also doesnt work, I tried both `object_sort` and `tag_sort` but attributes are not sorted

Here is what I'm doing:

```
const prettydiff = require('prettydiff2');

const myHTML = "<div data-banana='banana' id='idDiv' class='myClass' data-zoo='zoo'>hello</div>"

const beautifyOptions = {
  source: myHTML,
  mode: 'beautify',
  tag_sort: true,
}

const sortedHTML = prettydiff(beautifyOptions);
console.log(sortedHTML);
```

And I get this result:
```"<div data-banana='banana' id='idDiv' class='myClass' data-zoo='zoo'>hello</div>```

**Comment by prettydiff** [comment]
I can verify the *tag_sort* options is working correctly with this code:

```jsx
const prettydiff = require('prettydiff2');

const myHTML (<div data-banana='banana' id='idDiv' class='myClass' data-zoo='zoo'><x/><a/></div>);

const beautifyOptions = {
  source: myHTML,
  mode: 'beautify',
  tag_sort: true,
}

const sortedHTML = prettydiff(beautifyOptions);
console.log(sortedHTML);
```

Observations:
* The problem in the code you provided is that the markup is a string instead of actual markup code.
* The *tag_sort* option is designed to sort tags not attributes and it will correctly sort the `<x/>` and <a/>` tags.
* For HTML I automatically sort attributes.  I have that feature turned off for any sort of template language including JSX.  I can fix this by removing JSX from this line of code:  https://github.com/Unibeautify/sparser/blob/master/lexers/markup.ts#L445

Before I make any changes I need to do some research to see if this is harmful.  Honestly, JSX is kind of broken regarding these types of considerations.  The embedded markup was originally designed to be vanilla XML, but the language was extended away from that because younger developers don't know what XML is.  As a result JSX has unique white space rules that don't exist anywhere else and attribute order matters in some user cases even if it shouldn't.

Also in HTML these are equivalent `noValue` and `noValue="noValue"`.  In XML that would be an error but its easily fixed in a preprocessor.  In JSX this is also possibly unique for the same reasons.
