### ISSUE TITLE
what happened to .prettydiffrc ?

### ISSUE THREAD

**Issue by ctf0** [prettydiff/prettydiff#611]
am trying to use the lib through the cli but i cant find anywhere in the docs regarding using a config file

**Comment by prettydiff** [comment]
I did not bring that functionality into the latest version of Pretty Diff when I rewrote the application in TypeScript.  I wasn't sure if anybody was using it.  I will adapt the old logic to the current app.

**Comment by ctf0** [comment]
awesome, btw is there a chance to add a new option where the user can add opening & closing tags that should have a one indent level inside them ?

ex. (laravel blade)[https://laravel.com/docs/5.8/blade]

**Comment by prettydiff** [comment]
It looks like new tag support would need to be added to support the Laravel syntax.  I don't think this is anything that needs to be hidden behind an option.  If you are willing to work with me on this I can add that level of support.  I will create a new branch for Laravel support and I would you need to clone it down and test it with a variety of Laravel code samples so that you can let me know of the defects and lack of support.  Once everything is solid I will merge that branch back into master.

**Comment by ctf0** [comment]
yeah i can work it np, but actually the `@` symbol is found in many fw ex.vuejs,angular,blade

also the same rule applies to something like twig but with different syntax `{% something %}` instead of `@something`

so i was basically thinking of a way to tell the parser to add some extra tags on runtime instead of hard coding the logic into the package which will be hard to maintain

**Comment by ctf0** [comment]
thanx for adding the config file option back, can u plz tell me how to use it from the cli ?

atm i have 
```
prettydiff source:${file} output:${file} config:C:/Users/abc/.prettydiffrc
```

but it doesnt work

**Comment by prettydiff** [comment]
I was thinking about this on my morning run about two hours ago.  I have the .prettydiffrc located in the Pretty Diff project and that is the only location I am looking to for that file.  This doesn't make much sense since the file would always be overwritten every time the application is updated and it isn't helpful.

Instead I need to look for the file in a project's directory.  Here are the updated requirements I need to code out:

* From the starting point I need to look for the .prettydiffrc file in the starting point directory and if not present in the parent directory and so forth until root.
* In the case of `readmethod:screen` I need to look for the .prettydiffrc starting in the current working directory of the terminal.
* In all other cases I need to start from the file's location even if unrelated and outside the current working directory.
* I need to add more tests to ensure I am resolving the file in alternate locations.

**Comment by prettydiff** [comment]
I just updated the code to solve for this.  Please try it now and let me know if it still isn't working for you.  I added some documentation on this as well:  https://prettydiff.com/documentation.xhtml#prettydiffrc

**Comment by ctf0** [comment]
sorry for the late reply, i just saw it, the docs doesnt have a part for the cli usage, so just to confirm
```
prettydiff source:${file} output:${file} config:C:/Users/abc/.prettydiffrc
```
is the correct usage ?

**Comment by prettydiff** [comment]
Try putting the .prettydiffrc file in your project's directory and then beautifying from the command line.  You will need to specify the source location and a command, example:

`prettydiff beautify source:"/my/file/system"`

The way its configured right now all execution from the terminal happens in a file named *services.ts*.  It will look into the source location, if the source is a file system location, for the .prettydiffrc file.  If there is no such file in that directory it will look into the parent directory and continue looking into next parent until it reaches root.  I have not configured an option to specify a separate location for a .prettydiffrc.

Please let me know if this still doesn't work.

**Comment by ctf0** [comment]
what if instead of doing the config file lookup which i presume will run on each execution, the lib checks if a config arg was passed to the cli or fallback to defaults.

on a side note:
config already have a key for mode, why u still need it for the cli ? i think it should be used as a fallback if the mode key is not available.

**Comment by prettydiff** [comment]
> what if instead of doing the config file lookup which i presume will run on each execution, the lib checks if a config arg was passed to the cli or fallback to defaults.

I could easily add an option to allow a user to pass in a custom location for the .prettydiffrc file:

`prettydiff beautify source:"/Users/something/myfile.js" prettydiffrc:"/Users/other_project/sub_project/my_file_name.txt"`

At the moment if the .prettydiffrc file is not found then the application does fallback on defaults.  You are correct in that the application checks for the .prettydiffrc file at each execution.  If this is to not occur I can extend the previous option with a specific value:

`prettydiff beautify source:"/Users/something/myfile.js" prettydiffrc:"none"`

If I should not be checking for the file on each execution when should I be checking for the file or when should I tell the application to check for a different file?

> config already have a key for mode, why u still need it for the cli ? i think it should be used as a fallback if the mode key is not available.

That is a very good point.  The reason why mode is required is because at this time any supported command is required.  Try `prettydiff commands`.  What I can do is default to command **diff** if no command is specified but both the options *source* and *diff* are provided or default to **beautify** if the option *source* is provided but not the option *diff*.  I just need some command so that the application gets to the point where the .prettydiffrc file is resolved as it is only resolved for the commands: *beautify*, *diff*, *minify*, *parse*.

**Comment by ctf0** [comment]
> prettydiffrc:"/Users/other_project/sub_project/my_file_name.txt"

i would recommend using `config` instead to follow the cli standards.

> If this is to not occur I can extend the previous option with a specific value:
>
> prettydiff beautify source:"/Users/something/myfile.js" prettydiffrc:"none"

there is no need, the current impl is valid.

> If I should not be checking for the file on each execution when should I be checking for the file or when should I tell the application to check for a different file?

of-course the lib will have to check for the file path on each execution, but my solution was related to the file auto lookup, however you can also avoid this by using cache "like a .temp/.index file"

> I just need some command 

that's understandable, np then :+1:

**Comment by panoply** [comment]
Could be worth adding JSON Schema reference for users that will apply options in JSON format. Most editors provide support for this and can be a huge help

**Comment by ctf0** [comment]
@prettydiff hi again, any way to test the new config option ?

**Comment by ctf0** [comment]
@prettydiff any progress ?
