### ISSUE TITLE
Wrong substitution when using "++ and -- operator conversion"

### ISSUE THREAD

**Issue by nilsboy** [prettydiff/prettydiff#65]
Currently a++ gets replaced by a+= 1.
But a+=1 is actually equal to ++a.

```
> node -p "var a = 1 ; a+=1"                                                                     
2
> node -p "var a = 1 ; a++"                                                                      
1
> node -p "var a = 1 ; ++a"                                                                      
2
```

This breaks for example when used with arrays:

```javascript
    function setWindowId(ev, wid) {
        // set window in the event we are sending
        var n = wid;
        var offset = 12;
        var buf = ev.rawData;
        buf[offset++] = n & 0xff;
        buf[offset++] = (n >> 8) & 0xff;
        buf[offset++] = (n >> 16) & 0xff;
        buf[offset++] = (n >> 24) & 0xff;
    }
```

Also, please split the jscorrect option into their own option - i.e. jscorrect_inc, jscorrect_missing_curlies, etc. I would like to turn the inc correction off.

Thank you.

**Comment by prettydiff** [comment]
Up for your review:

http://prettydiff.com/ignore/testlocation/prettydiff.com.xhtml

Notes:

* Due to a long time regression bug I was not converting ++a (pre-increment)
* Pre-increment operator is only being converted if preceded by: "(", "), "[", "}", ",", ";", "return" and followed by ")", "]", "}", ";".
* Post-increment operator is only being converted if preceded by: "), "}", ";" and followed by ")", "]", "}", ";".

I will consider breaking this out from the correct option at a later time.
